FROM node:14

# ENV PORT 8080

WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY ./sod-server/package*.json ./

RUN npm ci
# run this for production
# npm ci --only=production

COPY ./sod-server/ .

# EXPOSE 8080

CMD [ "npm", "start" ]