name: Vormadal Diaper Tracker

on:
  push:
    branches:
      - "main"

jobs:
  # ci:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: 17
  #         distribution: 'zulu' # Alternative distribution options are available.
  #     - uses: actions/checkout@v3
  #       with: 
  #         fetch-depth: 0
  #     - name: Cache SonarCloud packages
  #       uses: actions/cache@v3
  #       with:
  #         path: ~\sonar\cache
  #         key: ${{ runner.os }}-sonar
  #         restore-keys: ${{ runner.os }}-sonar
  #     - name: Cache SonarCloud scanner
  #       id: cache-sonar-scanner
  #       uses: actions/cache@v3
  #       with:
  #         path: .\.sonar\scanner
  #         key: ${{ runner.os }}-sonar-scanner
  #         restore-keys: ${{ runner.os }}-sonar-scanner
  #     - name: Install SonarCloud scanner
  #       if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
  #       shell: pwsh
  #       run: |
  #         New-Item -Path .\.sonar\scanner -ItemType Directory
  #         dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
  #     - name: Build and analyze
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       shell: pwsh
  #       run: |
  #         .\.sonar\scanner\dotnet-sonarscanner begin /k:"vormadal_settlers-of-denmark" /o:"vormadal" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
  #         dotnet build "DiaperTracker.Backend/DiaperTracker.sln"
  #         .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      
  deploy:
    runs-on: windows-latest
    environment: Production
    # needs: [ci]
    steps:
      - uses: actions/checkout@v3 
      - name: Install Caprover
        run: yarn add caprover
      - name: Cache caprover
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Deploy server to Caprover
        run: >
          node_modules/.bin/caprover deploy -h https://captain.caprover.vormadal.com 
          -b ${{ github.ref }} 
          -c ../../captain-definition-server 
          --appToken ${{ secrets.CAPROVER_SERVER_APP_TOKEN }} 
          -a "sod-server" 

      - name: Deploy client to Caprover
        run: >
          node_modules/.bin/caprover deploy -h https://captain.caprover.vormadal.com 
          -b ${{ github.ref }} 
          -c ../../captain-definition-client 
          --appToken ${{ secrets.CAPROVER_CLIENT_APP_TOKEN }} 
          -a "sod-client" 
      # - name: Wait for deployment is done
      #   run: >
      #     node ./scripts/waitForDeploymentCompletion.js 
      #     appName=diaper-tracker
      #     password=${{ secrets.CAPROVER_PASSWORD }} 
      #     url=https://captain.caprover.vormadal.com 
      #     cwd=node_modules/.bin